spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3366/bookdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 7300
    password: '123456'

server:
  port: 8383

debug: true